# Generated by Django 6.1.1 on 2026-09-18 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('story', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('FULL_STACK', 'Full Stack'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('JAVASCRIPT', 'JavaScript'), ('REACT', 'ReactJS'), ('SQL', 'SQL'), ('POSTGRES', 'PostgreSQL'), ('GIT', 'Git / GitHub'), ('SCRUM', 'Scrum'), ('REGEX', 'Regex')], max_length=30)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Media'), ('HARD', 'Difícil')], default='EASY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_escape_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscapeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'En curso'), ('COMPLETED', 'Completada'), ('FAILED', 'Tiempo agotado'), ('ABANDONED', 'Abandonada')], default='ACTIVE', max_length=20)),
                ('current_order', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='escape_arenas.escaperoom')),
            ],
        ),
        migrations.CreateModel(
            name='EscapeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('narrative', models.TextField(blank=True)),
                ('statement', models.TextField()),
                ('category', models.CharField(choices=[('PYTHON', 'Python'), ('DJANGO', 'Django'), ('JAVASCRIPT', 'JavaScript'), ('REACT', 'ReactJS'), ('SQL', 'SQL'), ('POSTGRES', 'PostgreSQL'), ('GIT', 'Git / GitHub'), ('SCRUM', 'Scrum'), ('REGEX', 'Regex'), ('WEB', 'HTML / CSS')], max_length=30)),
                ('answer_type', models.CharField(choices=[('EXACT', 'Respuesta exacta'), ('CASE_INSENSITIVE', 'Texto sin distinguir mayúsculas'), ('MULTIPLE_CHOICE', 'Opción'), ('NORMALIZED_CODE', 'Código normalizado'), ('REGEX_PATTERN', 'Patrón Regex')], max_length=30)),
                ('expected_answer', models.TextField()),
                ('points', models.PositiveIntegerField(default=100)),
                ('hint_text', models.TextField(blank=True)),
                ('hint_penalty', models.PositiveIntegerField(default=25)),
                ('max_attempts', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='escape_arenas.escaperoom')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EscapeHintUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_uses', to='escape_arenas.escapesession')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hint_uses', to='escape_arenas.escapestage')),
            ],
        ),
        migrations.CreateModel(
            name='EscapeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='escape_arenas.escapesession')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='escape_arenas.escapestage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='escapestage',
            constraint=models.UniqueConstraint(fields=('room', 'order'), name='unique_stage_order_per_room'),
        ),
        migrations.AddConstraint(
            model_name='escapehintuse',
            constraint=models.UniqueConstraint(fields=('session', 'stage'), name='unique_hint_per_stage_session'),
        ),
    ]
