# Generated by Django 6.1.1 on 2026-10-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EscapeRoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallada'), ('ABANDONED', 'Abandonada')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=1800)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('statement', models.TextField()),
                ('expected_answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='escape_arenas.room')),
            ],
            options={
                'ordering': ['room', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakes_count', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='escape_arenas.escaperoomsession')),
                ('current_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='escape_arenas.room')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='escape_arenas.stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_attempts', to='escape_arenas.escaperoomsession')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='escape_arenas.stage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('room', 'order'), name='unique_stage_order_per_room'),
        ),
        migrations.AddConstraint(
            model_name='playerprogress',
            constraint=models.UniqueConstraint(fields=('session',), name='unique_progress_per_session'),
        ),
    ]
